=begin
#SurveyMonkey API V3

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.27
=end

require 'spec_helper'
require 'json'

# Unit tests for SurveyMonkeySwaggerClient::SurveyFolders_Api
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SurveyFolders_Api' do
  before do
    # run before each test
    @instance = SurveyMonkeySwaggerClient::SurveyFolders_Api.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SurveyFolders_Api' do
    it 'should create an instance of SurveyFolders_Api' do
      expect(@instance).to be_instance_of(SurveyMonkeySwaggerClient::SurveyFolders_Api)
    end
  end

  # unit tests for create_a_folder
  # Create a folder
  # Create a folder
  # @param [Hash] opts the optional parameters
  # @option opts [V3SurveyFoldersBody] :body
  # @return [nil]
  describe 'create_a_folder test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_a_folder
  # Delete a folder
  # Delete a folder
  # @param folder_id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_a_folder test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_a_folder
  # Get a folder
  # Get a folder
  # @param folder_id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_a_folder test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_all_folders
  # Get all folders
  # Get all folders
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_all_folders test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_a_folder
  # Update a folder
  # Update a folder
  # @param folder_id
  # @param [Hash] opts the optional parameters
  # @option opts [SurveyFoldersFolderIdBody] :body
  # @return [nil]
  describe 'update_a_folder test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
