=begin
#SurveyMonkey API V3

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.27
=end

require 'spec_helper'
require 'json'

# Unit tests for SurveyMonkeySwaggerClient::UsersAndGroupsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UsersAndGroupsApi' do
  before do
    # run before each test
    @instance = SurveyMonkeySwaggerClient::UsersAndGroupsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UsersAndGroupsApi' do
    it 'should create an instance of UsersAndGroupsApi' do
      expect(@instance).to be_instance_of(SurveyMonkeySwaggerClient::UsersAndGroupsApi)
    end
  end

  # unit tests for get_a_group_member
  # Get a group member
  # Return a group memeber&#x27;s details including their role and status
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_a_group_member test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_group_members
  # Get group members
  # Returns a list of users who have been added as members of the specified group
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_group_members test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_user_details
  # Get user details
  # Returns the current user&#x27;s account details including their plan
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_user_details test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_user_group
  # Get user group
  # Return a group if the user account belongs to a group (users can only belong to one group)
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_user_group test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_user_group_by_id
  # Get user group by id
  # Returns a group’s details including the group’s owner and email address
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_user_group_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
