=begin
#SurveyMonkey API V3

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.27
=end

require 'spec_helper'
require 'json'

# Unit tests for SurveyMonkeySwaggerClient::WebhooksApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WebhooksApi' do
  before do
    # run before each test
    @instance = SurveyMonkeySwaggerClient::WebhooksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhooksApi' do
    it 'should create an instance of WebhooksApi' do
      expect(@instance).to be_instance_of(SurveyMonkeySwaggerClient::WebhooksApi)
    end
  end

  # unit tests for create_a_webhooks
  # Create a  webhooks
  # Create a webhook
  # @param [Hash] opts the optional parameters
  # @option opts [V3WebhooksBody] :body
  # @return [nil]
  describe 'create_a_webhooks test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_a_webhook
  # Delete a webhook
  # Delete a webhook
  # @param webhook_id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_a_webhook test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_a_list_of_webhooks
  # Get a list of webhooks
  # Get a list of webhooks
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_a_list_of_webhooks test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_a_webhook_by_id
  # Get a webhook by id
  # Get a webhook by id
  # @param webhook_id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_a_webhook_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for modify_a_webhook
  # Modify a webhook
  # Modify a webhook
  # @param webhook_id
  # @param [Hash] opts the optional parameters
  # @option opts [WebhooksWEBHOOKIDBody1] :body
  # @return [nil]
  describe 'modify_a_webhook test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for replace_a_webhook
  # Replace a webhook
  # Replace a webhook
  # @param webhook_id
  # @param [Hash] opts the optional parameters
  # @option opts [WebhooksWEBHOOKIDBody] :body
  # @return [nil]
  describe 'replace_a_webhook test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
