=begin
#SurveyMonkey API V3 

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.27
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SurveyMonkeySwaggerClient::LanguagesLocaleBody1
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LanguagesLocaleBody1' do
  before do
    # run before each test
    @instance = SurveyMonkeySwaggerClient::LanguagesLocaleBody1.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LanguagesLocaleBody1' do
    it 'should create an instance of LanguagesLocaleBody1' do
      expect(@instance).to be_instance_of(SurveyMonkeySwaggerClient::LanguagesLocaleBody1)
    end
  end
  describe 'test attribute "enabled"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "translations"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
