=begin
#SurveyMonkey API V3

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.27
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SurveyMonkeySwaggerClient::Model310099766PagesBody
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Model310099766PagesBody' do
  before do
    # run before each test
    @instance = SurveyMonkeySwaggerClient::Model310099766PagesBody.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Model310099766PagesBody' do
    it 'should create an instance of Model310099766PagesBody' do
      expect(@instance).to be_instance_of(SurveyMonkeySwaggerClient::Model310099766PagesBody)
    end
  end
  describe 'test attribute "title"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
