=begin
#SurveyMonkey API V3 

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.27
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SurveyMonkeySwaggerClient::V3surveyssurveyIdlanguageslocaleTranslations
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'V3surveyssurveyIdlanguageslocaleTranslations' do
  before do
    # run before each test
    @instance = SurveyMonkeySwaggerClient::V3surveyssurveyIdlanguageslocaleTranslations.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of V3surveyssurveyIdlanguageslocaleTranslations' do
    it 'should create an instance of V3surveyssurveyIdlanguageslocaleTranslations' do
      expect(@instance).to be_instance_of(SurveyMonkeySwaggerClient::V3surveyssurveyIdlanguageslocaleTranslations)
    end
  end
  describe 'test attribute "context"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "default"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "resource_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "translation"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
