=begin
#SurveyMonkey API V3

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.27
=end

# Common files
require 'survey_monkey_swagger_client/api_client'
require 'survey_monkey_swagger_client/api_error'
require 'survey_monkey_swagger_client/version'
require 'survey_monkey_swagger_client/configuration'

# Models
require 'survey_monkey_swagger_client/models/collector_id_messages_body'
require 'survey_monkey_swagger_client/models/collector_id_responses_body'
require 'survey_monkey_swagger_client/models/contact_list_id_copy_body'
require 'survey_monkey_swagger_client/models/collectors_collector_id_body'
require 'survey_monkey_swagger_client/models/collectors_collector_id_body_1'
require 'survey_monkey_swagger_client/models/contact_fields_contact_field_id_body'
require 'survey_monkey_swagger_client/models/contact_lists_contact_list_id_body'
require 'survey_monkey_swagger_client/models/contact_lists_contact_list_id_body_1'
require 'survey_monkey_swagger_client/models/contacts_bulk_body'
require 'survey_monkey_swagger_client/models/contacts_bulk_body_1'
require 'survey_monkey_swagger_client/models/contacts_contact_id_body'
require 'survey_monkey_swagger_client/models/contacts_contact_id_body_1'
require 'survey_monkey_swagger_client/models/inline_response_200'
require 'survey_monkey_swagger_client/models/inline_response_201'
require 'survey_monkey_swagger_client/models/languages_locale_body'
require 'survey_monkey_swagger_client/models/languages_locale_body_1'
require 'survey_monkey_swagger_client/models/message_id_recipients_body'
require 'survey_monkey_swagger_client/models/message_id_send_body'
require 'survey_monkey_swagger_client/models/messages_message_id_body'
require 'survey_monkey_swagger_client/models/messages_message_id_body_1'
require 'survey_monkey_swagger_client/models/model_310099766_collectors_body'
require 'survey_monkey_swagger_client/models/model_310099766_pages_body'
require 'survey_monkey_swagger_client/models/page_id_questions_body'
require 'survey_monkey_swagger_client/models/pages_page_id_body'
require 'survey_monkey_swagger_client/models/pages_page_id_body_1'
require 'survey_monkey_swagger_client/models/questions_question_id_body'
require 'survey_monkey_swagger_client/models/questions_question_id_body_1'
require 'survey_monkey_swagger_client/models/recipients_bulk_body'
require 'survey_monkey_swagger_client/models/responses_response_id_body'
require 'survey_monkey_swagger_client/models/responses_response_id_body_1'
require 'survey_monkey_swagger_client/models/survey_folders_folder_id_body'
require 'survey_monkey_swagger_client/models/surveys_310099766_body'
require 'survey_monkey_swagger_client/models/surveys_310099766_body_1'
require 'survey_monkey_swagger_client/models/v3_contact_lists_body'
require 'survey_monkey_swagger_client/models/v3_contacts_body'
require 'survey_monkey_swagger_client/models/v3_survey_folders_body'
require 'survey_monkey_swagger_client/models/v3_surveys_body'
require 'survey_monkey_swagger_client/models/v3_webhooks_body'
require 'survey_monkey_swagger_client/models/v3collectors_collector_i_dmessages_message_i_drecipientsbulk_contacts'
require 'survey_monkey_swagger_client/models/v3collectors_collector_i_dmessages_message_i_drecipientsbulk_custom_fields'
require 'survey_monkey_swagger_client/models/v3collectors_collector_i_dmessages_message_i_drecipientsbulk_extra_fields'
require 'survey_monkey_swagger_client/models/v3collectors_collector_i_dresponses_answers'
require 'survey_monkey_swagger_client/models/v3collectors_collector_i_dresponses_pages'
require 'survey_monkey_swagger_client/models/v3collectors_collector_i_dresponses_questions'
require 'survey_monkey_swagger_client/models/v3contact_lists_contact_list_i_dcontactsbulk_contacts'
require 'survey_monkey_swagger_client/models/v3contactsbulk_contacts'
require 'survey_monkey_swagger_client/models/v3surveys310099766pages_page_i_dquestions_answers'
require 'survey_monkey_swagger_client/models/v3surveys310099766pages_page_i_dquestions_answers_choices'
require 'survey_monkey_swagger_client/models/v3surveys310099766pages_page_i_dquestions_headings'
require 'survey_monkey_swagger_client/models/v3surveys310099766pages_page_i_dquestions_question_id_answers'
require 'survey_monkey_swagger_client/models/v3surveys310099766pages_page_i_dquestions_question_id_answers_choices'
require 'survey_monkey_swagger_client/models/v3surveys310099766pages_page_i_dquestions_random_assignment'
require 'survey_monkey_swagger_client/models/v3surveyssurvey_idlanguageslocale_translations'
require 'survey_monkey_swagger_client/models/webhooks_webhook_id_body'
require 'survey_monkey_swagger_client/models/webhooks_webhook_id_body_1'

# APIs
require 'survey_monkey_swagger_client/api/benchmarks_api'
require 'survey_monkey_swagger_client/api/collectors_and_invite_messages_api'
require 'survey_monkey_swagger_client/api/contacts_and_contact_lists_api'
require 'survey_monkey_swagger_client/api/errors_api'
require 'survey_monkey_swagger_client/api/response_counts_and_trends_api'
require 'survey_monkey_swagger_client/api/survey_folders__api'
require 'survey_monkey_swagger_client/api/survey_responses_api'
require 'survey_monkey_swagger_client/api/surveys_pages_and_questions_api'
require 'survey_monkey_swagger_client/api/translations_for_multilingual_surveys_api'
require 'survey_monkey_swagger_client/api/users_and_groups_api'
require 'survey_monkey_swagger_client/api/webhooks_api'

module SurveyMonkeySwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SurveyMonkeySwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
